"""Import all mapped models so metadata is complete for Alembic and create_all."""

from cornerroom.infra.idempotency import IdempotencyRecord
from cornerroom.infra.outbox import OutboxEvent
from cornerroom.modules.artists.domain.models import (
    Artist,
    ArtistApplication,
    Band,
    BandMember,
    Follow,
)
from cornerroom.modules.music.domain.models import (
    Credit,
    Release,
    ReleaseTrack,
    Track,
    TrackVersion,
)
from cornerroom.modules.streaming.domain.models import (
    LibraryItem,
    ListeningSession,
    PlaybackEvent,
    Playlist,
    PlaylistItem,
)
from cornerroom.modules.audit.domain.models import AuditLog
from cornerroom.modules.authorization.domain.models import (
    Permission,
    ResourceGrant,
    Role,
    RoleAssignment,
    RolePermission,
)
from cornerroom.modules.documents.domain.models import (
    Document,
    DocumentAcl,
    DocumentVersion,
    MediaAsset,
)
from cornerroom.modules.events.domain.models import Event, EventLineup, EventMilestone, Venue, VenueBooking
from cornerroom.modules.ticketing.domain.models import (
    CheckIn,
    RefundPolicy,
    Ticket,
    TicketHold,
    TicketType,
    TicketTypeInventory,
)
from cornerroom.modules.commerce.domain.models import (
    Offer,
    Order,
    OrderItem,
    Product,
    RefundEntitlementPolicy,
    TaxLine,
)
from cornerroom.modules.entitlements.domain.models import Entitlement
from cornerroom.modules.finance.domain.models import (
    Adjustment,
    Expense,
    ExpenseCategory,
    FinanceConfig,
    FinanceTransaction,
    Invoice,
    InvoiceLine,
    LedgerAccount,
    LedgerEntry,
    PayeeCompliance,
    Payment,
    PaymentAttempt,
    Payout,
    PayoutMethod,
    ReconciliationItem,
    Refund,
    Revenue,
)
from cornerroom.modules.subscriptions.domain.models import (
    Subscription,
    SubscriptionPeriod,
    SubscriptionPlan,
    SubscriptionPlanVersion,
)
from cornerroom.modules.royalties.domain.models import (
    RecognizedRevenueIntake,
    RevenuePool,
    RightShare,
    Rights,
    Royalty,
    RoyaltyAdjustment,
    RoyaltyLine,
    RoyaltyRule,
    RoyaltyStatement,
    Settlement,
    SettlementLine,
)
from cornerroom.modules.identity.domain.models import (
    CustomerProfile,
    IdentityChallenge,
    Organization,
    OrganizationInvitation,
    OrganizationMembership,
    Session,
    User,
)
from cornerroom.modules.notifications.domain.models import (
    Notification,
    NotificationDelivery,
    NotificationPreference,
    NotificationTemplate,
)

__all__ = [
    "Artist",
    "ArtistApplication",
    "AuditLog",
    "Band",
    "BandMember",
    "CheckIn",
    "Credit",
    "CustomerProfile",
    "IdentityChallenge",
    "Document",
    "DocumentAcl",
    "DocumentVersion",
    "Event",
    "EventLineup",
    "EventMilestone",
    "Follow",
    "IdempotencyRecord",
    "LibraryItem",
    "ListeningSession",
    "PlaybackEvent",
    "Playlist",
    "PlaylistItem",
    "MediaAsset",
    "Release",
    "ReleaseTrack",
    "Track",
    "TrackVersion",
    "Notification",
    "NotificationDelivery",
    "NotificationPreference",
    "NotificationTemplate",
    "Organization",
    "OrganizationInvitation",
    "OrganizationMembership",
    "Entitlement",
    "Offer",
    "Order",
    "OrderItem",
    "OutboxEvent",
    "Payment",
    "PaymentAttempt",
    "Product",
    "Refund",
    "Adjustment",
    "Expense",
    "ExpenseCategory",
    "FinanceConfig",
    "FinanceTransaction",
    "Invoice",
    "InvoiceLine",
    "LedgerAccount",
    "LedgerEntry",
    "PayeeCompliance",
    "Payout",
    "PayoutMethod",
    "ReconciliationItem",
    "Revenue",
    "RefundEntitlementPolicy",
    "Subscription",
    "SubscriptionPeriod",
    "SubscriptionPlan",
    "SubscriptionPlanVersion",
    "Permission",
    "RefundPolicy",
    "RecognizedRevenueIntake",
    "RevenuePool",
    "RightShare",
    "Rights",
    "Royalty",
    "RoyaltyAdjustment",
    "RoyaltyLine",
    "RoyaltyRule",
    "RoyaltyStatement",
    "Settlement",
    "SettlementLine",
    "ResourceGrant",
    "Role",
    "RoleAssignment",
    "RolePermission",
    "Session",
    "TaxLine",
    "Ticket",
    "TicketHold",
    "TicketType",
    "TicketTypeInventory",
    "User",
    "Venue",
    "VenueBooking",
]
